version: 2.1

executors:
  nodejs:
    docker:
      - image: cimg/python:3.9.6
    resource_class: medium

commands:
  config_machine:
    steps:
      - run:
          name: Configurando maquina
          command: |
            echo -e "\033[7;92m INSTALANDO NODEJS"
            curl -sL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
            sudo apt-get -y install nodejs
jobs:
  deploy:
    executor: nodejs
    steps:
      - checkout
      - config_machine
      - run: chmod +x scripts/*
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Build application
          command: npm run build
      - run: ./scripts/install_terraform.sh
      - run:
          name: Terraform Build
          command: |
            cd terraform
            terraform init
            terraform fmt
            terraform validate
            terraform apply


workflows:
  deploy-dev:
    jobs:
      - deploy:
          name: Deploy dev
          context: awsAccount
          filters:
            branches:
              only: dev