version: 2.1

executors:
  nodejs:
    docker:
      - image: cimg/node:18.7.0
    resource_class: medium

orbs: 
  aws-cli: circleci/aws-cli@3.1
  terraform: circleci/terraform@3.1.0

jobs:
  deploy:
    executor: nodejs
    parameters:
      deploy-env:
        type: enum
        enum: ["dev"]
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: personal
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Build application
          command: npm run build
      - terraform/install:
          arch: amd64
          os: linux
          terraform_version: 0.14.2
      - terraform/fmt:
          path: terraform
      - terraform/validate:
          path: terraform 
      - terraform/init:
          path: terraform
      - terraform/plan:
          var_file: <<parameters.deploy-env>>/terraform.tfvars
          path: terraform
      - terraform/apply:
          var_file: <<parameters.deploy-env>>/terraform.tfvars
          path: terraform
      
workflows:
  deploy-dev:
    jobs:
      - deploy:
          name: Deploy dev
          context: awsAccount
          deploy-env: dev
          filters:
            branches:
              only: dev