version: 2.1

executors:
  nodejs:
    docker:
      - image: circleci/node:erbium-bullseye-browsers-legacy

jobs:
  deploy:
    executor: nodejs
    steps:
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Build application
          command: npm build
      - run:
          name: Terraform Build
          command: |
            cd terraform
            terraform init
            terraform fmt
            terraform validate
            terraform apply

workflows:
  deploy-dev:
    jobs:
      - deploy:
          name: Deploy dev
          context: awsAccount
          filters:
            branches:
              only: dev