version: 2.1

executors:
  nodejs:
    docker:
      - image: circleci/node:erbium-bullseye-browsers-legacy
    resource_class: medium

orbs:
  terraform: circleci/terraform@3.1

jobs:
  deploy:
    executor: nodejs
    steps:
      - run: chmod +x scripts/*
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Build application
          command: npm build
      - run: 
      - run:
          name: Terraform Build
          command: |
            cd $HOME/project
            ls


workflows:
  deploy-dev:
    jobs:
      - deploy:
          name: Deploy dev
          context: awsAccount
          filters:
            branches:
              only: dev